/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReglementationsRouteImport } from './routes/reglementations'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournauxRouteImport } from './routes/journaux'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as AbonnementsRouteImport } from './routes/abonnements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LecteurEditionIdRouteImport } from './routes/lecteur.$editionId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglementationsRoute = ReglementationsRouteImport.update({
  id: '/reglementations',
  path: '/reglementations',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournauxRoute = JournauxRouteImport.update({
  id: '/journaux',
  path: '/journaux',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const AbonnementsRoute = AbonnementsRouteImport.update({
  id: '/abonnements',
  path: '/abonnements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LecteurEditionIdRoute = LecteurEditionIdRouteImport.update({
  id: '/lecteur/$editionId',
  path: '/lecteur/$editionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abonnements': typeof AbonnementsRoute
  '/administration': typeof AdministrationRoute
  '/categories': typeof CategoriesRoute
  '/documents': typeof DocumentsRoute
  '/favoris': typeof FavorisRoute
  '/journaux': typeof JournauxRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profil': typeof ProfilRoute
  '/recherche': typeof RechercheRoute
  '/reglementations': typeof ReglementationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/lecteur/$editionId': typeof LecteurEditionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abonnements': typeof AbonnementsRoute
  '/administration': typeof AdministrationRoute
  '/categories': typeof CategoriesRoute
  '/documents': typeof DocumentsRoute
  '/favoris': typeof FavorisRoute
  '/journaux': typeof JournauxRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profil': typeof ProfilRoute
  '/recherche': typeof RechercheRoute
  '/reglementations': typeof ReglementationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/lecteur/$editionId': typeof LecteurEditionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abonnements': typeof AbonnementsRoute
  '/administration': typeof AdministrationRoute
  '/categories': typeof CategoriesRoute
  '/documents': typeof DocumentsRoute
  '/favoris': typeof FavorisRoute
  '/journaux': typeof JournauxRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profil': typeof ProfilRoute
  '/recherche': typeof RechercheRoute
  '/reglementations': typeof ReglementationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/lecteur/$editionId': typeof LecteurEditionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abonnements'
    | '/administration'
    | '/categories'
    | '/documents'
    | '/favoris'
    | '/journaux'
    | '/login'
    | '/notifications'
    | '/profil'
    | '/recherche'
    | '/reglementations'
    | '/reset-password'
    | '/lecteur/$editionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abonnements'
    | '/administration'
    | '/categories'
    | '/documents'
    | '/favoris'
    | '/journaux'
    | '/login'
    | '/notifications'
    | '/profil'
    | '/recherche'
    | '/reglementations'
    | '/reset-password'
    | '/lecteur/$editionId'
  id:
    | '__root__'
    | '/'
    | '/abonnements'
    | '/administration'
    | '/categories'
    | '/documents'
    | '/favoris'
    | '/journaux'
    | '/login'
    | '/notifications'
    | '/profil'
    | '/recherche'
    | '/reglementations'
    | '/reset-password'
    | '/lecteur/$editionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbonnementsRoute: typeof AbonnementsRoute
  AdministrationRoute: typeof AdministrationRoute
  CategoriesRoute: typeof CategoriesRoute
  DocumentsRoute: typeof DocumentsRoute
  FavorisRoute: typeof FavorisRoute
  JournauxRoute: typeof JournauxRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfilRoute: typeof ProfilRoute
  RechercheRoute: typeof RechercheRoute
  ReglementationsRoute: typeof ReglementationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LecteurEditionIdRoute: typeof LecteurEditionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglementations': {
      id: '/reglementations'
      path: '/reglementations'
      fullPath: '/reglementations'
      preLoaderRoute: typeof ReglementationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journaux': {
      id: '/journaux'
      path: '/journaux'
      fullPath: '/journaux'
      preLoaderRoute: typeof JournauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnements': {
      id: '/abonnements'
      path: '/abonnements'
      fullPath: '/abonnements'
      preLoaderRoute: typeof AbonnementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecteur/$editionId': {
      id: '/lecteur/$editionId'
      path: '/lecteur/$editionId'
      fullPath: '/lecteur/$editionId'
      preLoaderRoute: typeof LecteurEditionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbonnementsRoute: AbonnementsRoute,
  AdministrationRoute: AdministrationRoute,
  CategoriesRoute: CategoriesRoute,
  DocumentsRoute: DocumentsRoute,
  FavorisRoute: FavorisRoute,
  JournauxRoute: JournauxRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfilRoute: ProfilRoute,
  RechercheRoute: RechercheRoute,
  ReglementationsRoute: ReglementationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LecteurEditionIdRoute: LecteurEditionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
