
ALTER TABLE public.news_feed ADD CONSTRAINT news_feed_url_unique UNIQUE (url);

INSERT INTO public.news_feed (title, source, url, image_url, summary, published_at) VALUES
('La BEAC maintient son taux directeur à 5%', 'Agence Ecofin', 'https://www.agenceecofin.com/finance/beac-taux-2026', 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800', 'La Banque des États de l''Afrique Centrale a confirmé sa politique monétaire restrictive pour contenir l''inflation dans la sous-région CEMAC.', NOW() - INTERVAL '2 hours'),
('Cameroun : croissance attendue à 4,2% en 2026', 'Investir au Cameroun', 'https://www.investiraucameroun.com/economie/croissance-2026', 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800', 'Le FMI révise à la hausse ses prévisions de croissance pour l''économie camerounaise, portée par les secteurs pétrolier et agricole.', NOW() - INTERVAL '5 hours'),
('Afriland First Bank ouvre une nouvelle agence à Douala', 'Cameroon Tribune', 'https://www.cameroon-tribune.cm/finance/afriland-douala', 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800', 'L''établissement bancaire renforce sa présence dans la capitale économique avec une agence flagship dédiée aux PME.', NOW() - INTERVAL '8 hours'),
('BVMAC : la capitalisation boursière franchit les 1000 milliards FCFA', 'Jeune Afrique', 'https://www.jeuneafrique.com/economie/bvmac-1000mds', 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800', 'La bourse régionale d''Afrique centrale enregistre une performance historique grâce aux émissions obligataires souveraines.', NOW() - INTERVAL '12 hours'),
('CEMAC : harmonisation des taxes sur les transactions numériques', 'Les Échos', 'https://www.lesechos.fr/afrique/cemac-taxes-numeriques', 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800', 'Les six États membres adoptent une réglementation commune pour encadrer le mobile money et les paiements électroniques.', NOW() - INTERVAL '18 hours'),
('Le franc CFA face aux mutations monétaires africaines', 'BFM Business', 'https://www.bfmtv.com/economie/fcfa-mutations', 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800', 'Décryptage des débats actuels autour de la réforme du franc CFA et de la création potentielle d''une monnaie unique CEDEAO.', NOW() - INTERVAL '1 day'),
('Eurobonds : le Cameroun lève 450 millions USD', 'Reuters Africa', 'https://www.reuters.com/africa/cameroon-eurobond', 'https://images.unsplash.com/photo-1579621970795-87facc2f976d?w=800', 'L''opération a été sursouscrite trois fois, témoignant de la confiance des investisseurs internationaux dans la signature camerounaise.', NOW() - INTERVAL '1 day 4 hours'),
('Inflation en zone CEMAC : retour progressif sous les 3%', 'Agence Ecofin', 'https://www.agenceecofin.com/inflation-cemac-2026', 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800', 'Les politiques monétaires coordonnées portent leurs fruits avec une décélération marquée des prix à la consommation.', NOW() - INTERVAL '2 days'),
('Microfinance : nouveau cadre prudentiel COBAC', 'Investir au Cameroun', 'https://www.investiraucameroun.com/cobac-microfinance', 'https://images.unsplash.com/photo-1601597111158-2fceff292cdc?w=800', 'La Commission Bancaire renforce les exigences de fonds propres pour les établissements de microfinance de catégorie 2.', NOW() - INTERVAL '2 days 6 hours'),
('Énergie : le Cameroun double sa capacité hydroélectrique', 'Jeune Afrique', 'https://www.jeuneafrique.com/cameroun-hydro', 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800', 'La mise en service du barrage de Nachtigal porte la production nationale à plus de 2000 MW, soutenant la croissance industrielle.', NOW() - INTERVAL '3 days')
ON CONFLICT (url) DO NOTHING;
